type: edge_sam
name: edge_sam_with_chinese_clip-r20240131
display_name: EdgeSAM-CN-CLIP ViT-B-16
# EdgeSAM
encoder_model_path:
  local:
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.2.0/edge_sam_encoder.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.2.0/edge_sam_decoder.onnx
# ChineseClip
model_type: cn_clip
model_arch: ViT-B-16
txt_model_path:
  local: F:\Github\X-AnyLabeling\weights\clip\vit-b-16.txt.fp16.onnx
  online:
img_model_path:
  local: F:\Github\X-AnyLabeling\weights\clip\vit-b-16.img.fp16.onnx
  online:
txt_extra_path:
  local: F:\Github\X-AnyLabeling\weights\clip\vit-b-16.txt.fp16.onnx.extra_file
  online:
img_extra_path:
  local: F:\Github\X-AnyLabeling\weights\clip\vit-b-16.img.fp16.onnx.extra_file
  online:
classes: []