type: grounding_sam
name: groundingdino_swinb_attn_fuse_sam_hq_vit_l_quant
display_name: GroundingSAM-SwinB with HQ-SAM-VitL-QInt8
# Grounding-DINO
model_type: groundingdino_swinb_cogcoor
model_path:
  local: E:\models\Xlabel\dino\groundingdino_fuse_attention.onnx
  online:
input_width: 1200
input_height: 800
box_threshold: 0.3
text_threshold: 0.25
# HQ-SAM
encoder_model_path:
  local: E:\models\Xlabel\sam_hq\sam_hq_vit_l_encoder_quant.onnx
  online:
decoder_model_path:
  local: E:\models\Xlabel\sam_hq\sam_hq_vit_l_decoder.onnx
  online:
input_size: 1024
max_width: 1024
max_height: 682
