type: grounding_sam2
name: groundingdino_swint_sam2_large-r20240806
display_name: GroundingSAM2
# Grounding-DINO (swint)
model_type: groundingdino_swint_ogc
model_path:
  local: F:\Github\X-AnyLabeling\weights\dino\groundingdino_swint_ogc_quant.onnx
  online:
input_width: 1200
input_height: 800
box_threshold: 0.3
text_threshold: 0.25
# Segment-Anything-2 (large)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.encoder.onnx
  online:
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.decoder.onnx
  online:
