type: grounding_dino
name: groundingdino_swint_ogc_quant-r20231024
display_name: GroundingDINO (SwinT-QInt8) IDEA
model_type: groundingdino_swint_ogc
model_path:
  local: F:\Github\X-AnyLabeling\weights\dino\groundingdino_swint_ogc_quant.onnx
  online:
input_width: 1200
input_height: 800
box_threshold: 0.3
text_threshold: 0.25
