type: segment_anything_2
name: sam2_hiera_small-r20240801
display_name: Segment Anything 2 (Small)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_small.encoder.onnx
  online:
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_small.decoder.onnx
  online: