type: segment_anything_2
name: sam2_hiera_large-r20240801
display_name: Segment Anything 2 (Large)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.encoder.onnx
  online:
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.decoder.onnx
  online: