type: segment_anything
name: segment_anything_vit_l_quant-r20230810
display_name: Segment Anything (ViT-Large Quant)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam\sam_vit_l_0b3195.encoder.quant.onnx
  online:
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam\sam_vit_l_0b3195.decoder.quant.onnx
  online:
input_size: 1024
max_width: 1024
max_height: 682
