type: segment_anything
name: segment_anything_vit_b_quant-r20230520
display_name: Segment Anything (ViT-Base Quant)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam\sam_vit_b_01ec64.encoder.quant.onnx
  online:
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam\sam_vit_b_01ec64.decoder.quant.onnx
  online:
input_size: 1024
max_width: 1024
max_height: 682
